Add mockery
cs3org/go-cs3apis pull request #58
Opened 2024-09-26 07:19 UTC by jessegeens

This PR adds a mockery config, and mockery steps in the github workflow, to automatically generate mocked interfaces. This will enable us to do easier unit testing. Currently, only a mock of the GatewayAPIClient has been generated.

This PR introduces a fix to #57

2024-09-26 09:03 UTC, diocas approved these changes

2024-09-26 09:36 UTC, glpatcern commented
This is awesome, thanks @jessegeens! Do I understand it right that you're committing in one go the step to autogenerate the mocked code and the (current) mocked code itself?

2024-09-26 09:56 UTC, glpatcern requested changes
Actually answering my own question the `run mockery` step is to be moved to a different CI, which will push a commit here (and has the credentials to do so). Will tell you later how ;)

2024-09-27 08:56 UTC, glpatcern approved these changes

2024-09-27 08:57 UTC, glpatcern commented
Let's see if the CI works - a priori the generated code could have been pushed by it but it's fine

2024-09-27 08:57 UTC, merged